services:
  web: 
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    container_name: ttestfluskapp
    stop_signal: SIGINT
    ports:
      - '8000:8000'
