---
- name: "Install testfluskapp"
  become: yes
  hosts: [proddeploy]
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: kirilljbee
        password: keCD_ACKJf?++(8
    - name: Pull testfluskapp:latest Docker container
      docker_image:
        name: kirilljbee/testfluskapp:latest
        source: pull
    - name: Run testfluskapp:latest Docker container
      docker_container:
        name: testfluskapp
        image: kirilljbee/testfluskapp:latest
        state: started
        ports:
          - "8000:8000"
    