---
- name: "Install testfluskapp"
  become: yes
  hosts: [proddeploy]
  var 
  tasks:
    - name: Stop Running testfluskapp_prod container
      docker_container:
        name: testfluskapp_prod
        state: absent
    - name: Remove testfluskapp_prod Image 
      shell: |
         docker rmi kirilljbee/testfluskapp:prod;
    - name: Log into DockerHub
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKERHUB_PASSWORD }}"
    # - name: Pull testfluskapp:latest Docker container
    #   docker_image:
    #     name: kirilljbee/testfluskapp:prod
    #     source: pull
    - name: Pull and Run testfluskapp:latest Docker container
      docker_container:
        name: testfluskapp_prod
        image: kirilljbee/testfluskapp:prod
        state: started
        ports:
          - "8000:8000"
    