---
- name: "Install testfluskapp"
  become: yes
  hosts: [proddeploy]
  tasks:
    # - name: Stop running testfluskapp_prod container
    #   docker_container:
    #     name: testfluskapp_prod
    #     state: stopped
    - name: Log into DockerHub
      docker_login:
        username: kirilljbee
        password: keCD_ACKJf?++(8
    - name: Pull testfluskapp:latest Docker container
      docker_image:
        name: kirilljbee/testfluskapp:prod
        source: pull
    - name: Run testfluskapp:latest Docker container
      docker_container:
        name: testfluskapp_prod
        image: kirilljbee/testfluskapp:prod
        state: started
        ports:
          - "8000:8000"
    